
/*
 * Малък vanilla JS зареждач на общи парчета HTML (header/footer),
  * за да не се копира едно и също съдържание във всяка страница.
   *
    * Употреба:  <div data-include="partials/header.html"></div>
     *
      * Когато всички <div data-include="..."> елементи на страницата са
       * заредени, се пуска събитие "partials:loaded" на document — по него
        * main.js стартира спинъра/анимациите, за да няма "мигане" на
         * навигацията/футъра при бавна мрежа.
          */
          (function () {
              "use strict";

                  function markActiveNavLink() {
                          var current = (location.pathname.split("/").pop() || "index.html");
                                  document.querySelectorAll(".navbar-nav .nav-link[data-page]").forEach(function (link) {
                                              var isActive = link.getAttribute("data-page") === current ||
                                                              (current === "" && link.getAttribute("data-page") === "index.html");
                                                                          link.classList.toggle("active", isActive);
                                                                                  });
                                                                                      }

                                                                                          function loadIncludes() {
                                                                                                  var nodes = Array.prototype.slice.call(document.querySelectorAll("[data-include]"));
                                                                                                          if (nodes.length === 0) {
                                                                                                                      document.dispatchEvent(new CustomEvent("partials:loaded"));
                                                                                                                                  return;
                                                                                                                                          }

                                                                                                                                                  var pending = nodes.length;
                                                                                                                                                          nodes.forEach(function (node) {
                                                                                                                                                                      var url = node.getAttribute("data-include");
                                                                                                                                                                                  fetch(url)
                                                                                                                                                                                                  .then(function (res) {
                                                                                                                                                                                                                      if (!res.ok) throw new Error("Неуспешно зареждане на " + url + " (" + res.status + ")");
                                                                                                                                                                                                                                          return res.text();
                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                          .then(function (html) {
                                                                                                                                                                                                                                                                                              node.outerHTML = html;
                                                                                                                                                                                                                                                                                                              })
                                                                                                                                                                                                                                                                                                                              .catch(function (err) {
                                                                                                                                                                                                                                                                                                                                                  console.error(err);
                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                  .finally(function () {
                                                                                                                                                                                                                                                                                                                                                                                                      pending -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                          if (pending === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  markActiveNavLink();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          document.dispatchEvent(new CustomEvent("partials:loaded"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (document.readyState === "loading") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      document.addEventListener("DOMContentLoaded", loadIncludes);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  loadIncludes();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })();
